GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title":"testatitle",
    "author":"testauthor",
    "url":"testurl"
}

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username":"testuser",
    "password":"testpassword"
}

###

GET http://localhost:3003/api/users